### ISSUE TITLE
🏗️🐳 Testing environment for new containers

### ISSUE THREAD

**Issue by bschwedler** [posit-dev/images-shared#28]
## Acceptance Criteria

```[tasklist]
### Issues in Epic
- [ ] PTD environment for deploying the container images
- [ ] Leverage Helm charts to create a deployment of the images
- [ ] Run platform-integration-tests against images
```

**Comment by bschwedler** [comment]
We have a multi-arch EKS cluster that we have been using for a while.
