### ISSUE TITLE
Add a `validate` command to `bakery`

### ISSUE THREAD

**Issue by ianpittwood** [posit-dev/images-shared#34]
Depends on #51 

`validate` would be a command that lints and error checks the `bakery.yaml` file in a project. This would help end users more easily identify configuration issues when problems arise or ensure that changes they are making won't impact CI.

## Tasks

- [ ] Add a `bakery validate` command
- [ ] Perform validation on _all_ files
- [ ] Do not fail-fast
- [ ] Present a list of validation errors in a human-readable format, building on #96
