### ISSUE TITLE
Prototype Docker images rewrite

### ISSUE THREAD

**Issue by ianpittwood** [posit-dev/images-shared#44]
## Background
The rstudio/rstudio-docker-products repo has a long history with both our internal staff and external users. While there are good elements of it that we would like to keep, such as:
- Abstraction of product complexity
- Parallel, structured image builds
- Consistent linting, validation, and vulnerability scans
- Mostly positive general operation

There are also many elements that make the repo a negative experience for both internal and external users such as:
- Large, overengineered images
- Large, overcomplicated tags
- Incomplete labeling
- Complex overly integrated build/test workflows
- Inconsistent vulnerability patches for in support product versions
- Overabundance of bridging Justfile commands
- Licensing operation inconsistencies
- Confusing, repetitive configurations
- Confusion over shared ownership of repo

## Goals 
In an attempt to resolve a majority of these issues, I want to prototype a large scale rewrite of the repository and propose it to the Platform and Product teams as a new way forward. In this prototype, I want to directly address:
- Division of responsibilities and ownership
  - Migrate from single repo to definitively owned individual repos for each component image
  - Move Platform's role from image ownership to common fabric/tools ownership
  - Give team's full responsibility and governance over their images with Platform in an advisory capacity
- Overly integrated and complex workflows
  - Dividing up repositories will sever build interdependence of unrelated product team builds
  - We can still share workflow code via Platform team shared code
- Image size
  - Remove Python/R version duplication and strip out as many unrelated libraries as possible for product images
  - Provide a "minimal" image that does not include dependencies such as Python and R out of the box
- Overuse of Just commands
  - Move logic in Just code to maintainable and testable CLI tool for negotiating configurations with varying tools such as Bake, Goss, Snyk, etc.
- Confusing, repetitive configurations
  - Use explicit versions in image definitions
  - Create a template configuration that can be used for all images

## Acceptance Criteria
- [ ] Prototype a common tool that removes complexity around configuration and tool integration
- [ ] Prototype a common configuration format that reduces configuration repetition across projects
- [ ] Prototype a slimmed down base image that includes only the Ubuntu base OS and helper scripts for use downstream
- [ ] Prototype each product image in the new standard/minimal formats
- [ ] Document extending of images downstream
- [ ] Get buy-in from product teams on new prototype

## Issues In This Epic

```[tasklist]
### Issues
- [ ] https://github.com/rstudio/posit-images-shared/issues/43
- [x] Presentation across Posit Products teams of docker images
- [ ] https://github.com/rstudio/platform-team/issues/421
```
